# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  taskservice:
    image: taskservice
    build:
      context: .
      dockerfile: src/TaskService.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5018:5018
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
